# Generated by Django 5.1.6 on 2025-03-01 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('state', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=180)),
                ('sex', models.CharField(choices=[('Masculino', 'Male'), ('Femenino', 'Female')], max_length=10)),
                ('state', models.BooleanField(default=True)),
                ('birthdate', models.DateField(default=None, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=None, null=True)),
                ('customer_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customertype')),
            ],
        ),
    ]
